services:
  app:
    container_name: django-games-blog-app
    build: .
    command: sh -c "./entrypoint.sh
                python manage.py makemigrations &&
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - ./:/app
      - media:/app/media
      - static:/app/static
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    container_name: django-games-blog-db
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data_local:/var/lib/postgresql/data/


  redis:
    container_name: django-local-redis
    image: redis:alpine
    ports:
      - "6379:6379"
  celery:
    build: .
    container_name: django-celery-worker
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app
      - media:/app/media
    command: celery -A games_blog worker --loglevel=info --logfile=/app/logs/celery-worker.log
    depends_on:
      - redis

  beat:
    build: .
    container_name: django-celery-beat
    env_file:
      - .env
    depends_on:
      - redis
    command: celery -A games_blog beat --loglevel=info --logfile=/app/logs/celery-beat.log
    volumes:
      - media:/app/media
      - ./:/app
  nginx:
    build:
      context: ./nginx
    restart: always
    volumes:
      - static:/app/static
      - media:/app/media
    ports:
      - "80:80"
    depends_on:
      - app
volumes:
  postgres_data_local:
  static:
  media: