# Generated by Django 4.2.16 on 2024-11-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_options_profile_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="profile/avatars/default.jpg",
                upload_to="profile/avatars/%Y/%m/%d",
                verbose_name="Аватар",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, verbose_name="URL"),
        ),
    ]
