# Generated by Django 4.2.16 on 2024-11-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_article_author_alter_article_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                max_length=250,
                unique=True,
                unique_for_date="publish",
                verbose_name="URL",
            ),
        ),
    ]
