# Generated by Django 4.2.16 on 2024-11-16 23:55

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0004_alter_article_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "default_manager_name": "published",
                "ordering": ("-created_at",),
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.AlterModelManagers(
            name="article",
            managers=[
                ("published", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name="article",
            name="short_description",
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("email", models.EmailField(max_length=254)),
                ("content", models.TextField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comments",
                        to="blog.article",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
