# Generated by Django 4.2.16 on 2024-11-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_comment_options_remove_comment_user_and_more"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="comment",
        #     name="user",
        # ),
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(max_length=15),
        ),
    ]
