# Generated by Django 4.2.16 on 2024-11-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_user_alter_comment_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
