# Generated by Django 4.2.16 on 2024-11-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_comment_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="short_description",
            field=models.TextField(
                default="", max_length=150, verbose_name="Краткое описание"
            ),
        ),
    ]
