# Generated by Django 4.2.16 on 2024-11-20 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_comment_options_comment_parent_comment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="comment",
            name="lft",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="rght",
            field=models.PositiveIntegerField(default=2, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, editable=False),
            preserve_default=False,
        ),
    ]
