# Generated by Django 4.2.16 on 2024-11-21 00:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0013_alter_comment_level_feedback"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="article",
            name="blog_articl_publish_2a54df_idx",
        ),
        migrations.AddField(
            model_name="article",
            name="updater",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updater_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Обновил",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_articles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="blog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default_avatar/default.jpg",
                upload_to="posts/%m/%d",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
                verbose_name="Превью поста",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="views",
            field=models.PositiveIntegerField(default=0, verbose_name="Просмотры"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["-publish", "-created_at"],
                name="blog_articl_publish_8da7bb_idx",
            ),
        ),
    ]
