# Generated by Django 4.2.16 on 2024-11-21 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_alter_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                default="posts/default_article.png",
                upload_to="posts/%Y/%m/%d",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
                verbose_name="Превью поста",
            ),
        ),
    ]
