# Generated by Django 4.2.16 on 2024-11-21 14:50

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_alter_article_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="full_description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Полное описание"),
        ),
        migrations.AlterField(
            model_name="article",
            name="short_description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                default="", max_length=150, verbose_name="Краткое описание"
            ),
        ),
    ]
