# Generated by Django 4.2.16 on 2024-11-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_alter_article_full_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="ip_address",
            field=models.GenericIPAddressField(
                default="0.0.0.0", verbose_name="IP Адрес"
            ),
            preserve_default=False,
        ),
    ]
