# Generated by Django 4.2.16 on 2024-11-26 16:43

import django_ckeditor_5.fields

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_alter_article_publish_alter_comment_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="publish",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Назначенное публикации"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="short_description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, default="", max_length=55, verbose_name="Краткое описание"
            ),
        ),
    ]
