# Generated by Django 4.2.16 on 2024-11-26 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0020_alter_article_publish_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="views",
        ),
        migrations.CreateModel(
            name="ArticleView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP адрес")),
                (
                    "viewed_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата просмотра"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="blog.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Просмотр",
                "verbose_name_plural": "Просмотры",
                "ordering": ("-viewed_on",),
                "indexes": [
                    models.Index(
                        fields=["-viewed_on"], name="blog_articl_viewed__adc620_idx"
                    )
                ],
            },
        ),
    ]
