"""
Django settings for games_blog project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import environ
from sample_taggit.settings import BASE_DIR

env = environ.Env(
    DEBUG=(bool),
    SECRET_KEY=(str),
    DOMAIN_MAIN=(str),
    REDIS_HOST=(str),
    REDIS_PORT=(int),
    DATABASE_NAME=(str),
    DATABASE_USER=(str),
    DATABASE_PASS=(int),
    DATABASE_HOST=(str),
    DATABASE_PORT=(int),
    GITHUB_KEY=(str),
    GITHUB_SECRET=(str),
    VK_OAUTH2_KEY=(str),
    VK_OAUTH2_SECRET=(str),
    GOOGLE_OAUTH2_KEY=(str),
    GOOGLE_OAUTH2_SECRET=(str),
    INTERNAL_IPS=(str),
    CSRF_TRUSTED_ORIGINS=(str),
    RECAPTCHA_PUBLIC_KEY=(str),
    RECAPTCHA_PRIVATE_KEY=(str),
    EMAIL_HOST=(str),
    EMAIL_HOST_USER=(str),
    EMAIL_HOST_PASSWORD=(int),
    EMAIL_PORT=(int),
    EMAIL_USE_TLS=(bool),
    SOCIAL_AUTH_VK_OAUTH2_SCOPE=(str),
    SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE=(str),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ENV_PATH = BASE_DIR / ".env"
environ.Env.read_env(ENV_PATH)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env("ALLOWED_HOSTS").split()

DOMAIN_MAIN = env("DOMAIN_MAIN")

# Application definition

INSTALLED_APPS = [
    "channels",
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django.contrib.postgres",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    "debug_toolbar",
    "mptt",
    "taggit",
    "rest_framework",
    "django_filters",
    "social_django",
    "drf_spectacular",
    "django_mptt_admin",
    "captcha",
    "django_ckeditor_5",
    "rosetta",
    "django_extensions",
    "blog.apps.BlogConfig",
    "users.apps.UsersConfig",
    "api.apps.ApiConfig",
    "chat.apps.ChatConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "users.middleware.ActiveUserMiddleware",
]

ROOT_URLCONF = "games_blog.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
                "social_django.context_processors.login_redirect",
            ],
        },
    },
]

# Type Application
WSGI_APPLICATION = "games_blog.wsgi.application"
ASGI_APPLICATION = "games_blog.asgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
    }
}

# Redis
REDIS_HOST = env("REDIS_HOST")
REDIS_PORT = env("REDIS_PORT")

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}
# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

INTERNAL_IPS = [
    env("INTERNAL_IPS"),
]

CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/1"
CELERY_RESULT_BACKEND = f"redis://{REDIS_HOST}:{REDIS_PORT}/1"

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"
STATICFILES_DIRS = [BASE_DIR / "games_blog/static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Emails
EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
EMAIL_FILE_PATH = BASE_DIR / 'email_messages'
# Конфигурация сервера электронной почты
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
EMAIL_PORT = env("EMAIL_PORT")
EMAIL_USE_TLS = env("EMAIL_USE_TLS")

# Sites
# когда появилось еще одно приложение
SITE_ID = 1

SESSION_COOKIE_AGE = 60 * 60 * 24 * 30

AUTHENTICATION_BACKENDS = (
    "social_core.backends.github.GithubOAuth2",
    "social_core.backends.google.GoogleOAuth2",
    "django.contrib.auth.backends.ModelBackend",
)

# social auth configs for GitHub
SOCIAL_AUTH_GITHUB_KEY = env("GITHUB_KEY")
SOCIAL_AUTH_GITHUB_SECRET = env("GITHUB_SECRET")
SOCIAL_AUTH_VK_OAUTH2_KEY = env("VK_OAUTH2_KEY")
SOCIAL_AUTH_VK_OAUTH2_SECRET = env("VK_OAUTH2_SECRET")
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = env("GOOGLE_OAUTH2_KEY")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = env("GOOGLE_OAUTH2_SECRET")
SOCIAL_AUTH_VK_OAUTH2_SCOPE = [env("SOCIAL_AUTH_VK_OAUTH2_SCOPE")]
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [env("SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE")]

# CSRF
CSRF_TRUSTED_ORIGINS = ["http://*"]

# DRF
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 3,
}

# OpenAPI
SPECTACULAR_SETTINGS = {
    "TITLE": "GameBlog API Project",
    "DESCRIPTION": "A sample blog to learn about DRF",
    "VERSION": "1.0.0",
}
# Tags
TAGGIT_STRIP_UNICODE_WHEN_SLUGIFYING = True

RECAPTCHA_PUBLIC_KEY = env("RECAPTCHA_PUBLIC_KEY")
RECAPTCHA_PRIVATE_KEY = env("RECAPTCHA_PRIVATE_KEY")

# Captcha
CAPTCHA_MATH_CHALLENGE_OPERATOR = "x"
CAPTCHA_IMAGE_SIZE = (130, 60)

LOGIN_URL = "/users/login/"

# i18n
LANGUAGES = [
    ("en", "English"),
    ("ru", "Russian"),
]
LOCALE_PATHS = [
    BASE_DIR / "locale",
]

CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}

# Celery
CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_QUEUES = {
    "emails": {"exchange": "emails", "binding_key": "emails"},
    "published": {"exchange": "published", "binding_key": "published"},
}


# CKEEditor

CKEDITOR_5_FILE_UPLOAD_PERMISSION = "staff"
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                    'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],
        'language': 'ru',
    },
    'awesome_ckeditor': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
                    'code', 'subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
                    'bulletedList', 'numberedList', 'todoList', '|', 'blockQuote', 'imageUpload', '|',
                    'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
                    'insertTable', ],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side', '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]

        },

    }
}
# Pagination
PAGINATE_BY = 2